config/routes.rb
Rails.application.routes.draw do

  root 'users#home'
  
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}, path: :accounts

  resources :users, only: :show, path: :profile do
    resources :picks, except: :patch
  end

  resources :teams, only: [:index, :show]

  patch '/users/:user_id/picks/:id', to: 'picks#show', as: 'picks'

  get '/league', to: 'users#index'

  get '/schedule', to: 'games#schedule'

end

app/models/pick.rb
class Pick < ApplicationRecord
    belongs_to :user
    belongs_to :team
    belongs_to :week
  
    validates :team_id, :presence => true
  
    validate :user_quota, :on => :create
    # validate :loss, :on => :create


    
    def self.valid_pick?(pick)
      pick.team.bye == Week.current_week.id
    end
  
    private 
  
    def user_quota
      if user.picks.this_week.count >= 1
       errors.add(:base, "Your Pick has already been made, please edit your current pick.")
     end
    end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
    before_action :authenticate_user!
    # before_action :access?


    def index
        @picks = current_user.picks
        # Game.get_game(@picks)
        if helpers.access?(params) 
            redirect_to user_picks_path(current_user)
        end
    end
    
    def show

    end

    def new        
        @user = current_user
        @pick = Pick.new
        if helpers.access?(params) 
            redirect_to new_user_pick_path(current_user)
        end
    end

    def create
        @pick = current_user.picks.new(picks_params)
        @user = current_user
        @pick.week = Week.current_week

        if (Pick.valid_pick?(@pick))
            render :new, alert: 'Your selected team is on Bye. Please try again.'
        end
        if @pick.save
            redirect_to user_picks_path
        else
            render :new
        end
    end

    def edit
        @user = current_user
        if @pick = current_user.picks.find_by_id(params[:id])
        else
            redirect_to user_picks_path, alert: 'Invalid Pick. Please try again.'
        end
    end

    def update
        @pick = current_user.picks.find_by_id(params[:id])
        @pick.update(picks_params)
        if (Pick.valid_pick?(@pick))
            render :edit, alert: 'Your selected team is on Bye. Please try again.'
        end
        if @pick.save
          redirect_to user_picks_path
        else
          render :edit
        end
    end

    def destroy
        Pick.find(params[:id]).delete
        redirect_to user_picks_path
    end

    private

    def picks_params
        params.require(:pick).permit(:team_id, :buy_in)
    end
end

app/helpers/picks_helper.rb
module PicksHelper

end

app/views/picks/_form.html.erb
<%= form_for [@user, @pick], html: {class: "border border-light p-5"} do |f| %>
    <% if @pick.errors.any? %>
        <div id= "error_explanation">
            <% @pick.errors.full_messages.each do |message| %>
                <em style="color:red;font-size:12px;" > <%= message %> </em>
            <% end %>
        </div>
    <% end %>

    <div class="form-group">
    <label> Team </label><br>
        <%= f.collection_select(:team_id, current_user.remaining_teams, :id, :name, html: {class: "form-control form-control-lg"}) %>
    </div>

    <div class="form-group">
    <%= f.label :buy_in %>:<br>


    <%=f.select :buy_in, [['TRUE', true], ['FALSE', false]]%>
    </div>
    <div class="actions">
    <%= f.submit 'Create Pick', class: 'btn btn-info btn-block my-4'%>
    </div>
<% end %>

app/views/picks/_intro.html.erb
<h1> Welcome to Week <%= current_week.id %> </h1>
<p> Remember, once you pick a team, you can no longer pick them for the rest of the season. So chose wisely </p> <br>
<br>
<br>

app/views/picks/_table.html.erb
<br>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Week</th>
      <th>Picked Team</th>
      <th></th>
      <th>Date Picked</th>
      <th>Date of Game</th>
      <th>Outcome</th>
      <th>Buy In?</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% picks.each do |p|%>
    <tr>
      <td style='font-size:13px;'>Week <%= p.week.id%></td>
      <td style='font-size:13px;'><%= p.team.name %></td>
      <% if (p.week == current_week) && (params[:user_id].to_i == current_user.id) %>
        <td style='font-size:13px;'><%= link_to 'Edit Pick', edit_user_pick_path(p.user, p)%> - <%= link_to 'Delete Pick', user_pick_path(p.user, p), method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <%else%>
        <td></td>
      <%end%>
      <td style='font-size:13px;'><%= p.updated_at.localtime.strftime('%A, %B %dth')%></td>
      <td style='font-size:13px;'> <%= get_game(p).date.to_time.localtime.strftime('%A, %B %dth')%></td>

      <% if get_game(p).status == "UNPLAYED"%>
        <td style="color:red; font-size:13px;"><%= get_game(p).status %></td>
      <% else %>
        <td style='font-size:13px;'><%= get_game(p).winner.name %>
      <% end %>
      <td style='font-size:13px;'><%= p.buy_in%></td>
      <%         binding.pry %>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/picks/_test.html.erb
    <% if @pick.errors.any? %>
        <div id= "error_explanation">
            <% @pick.errors.full_messages.each do |message| %>
                <em style="color:red;font-size:12px;" > <%= message %> </em>
            <% end %>
        </div>
    <% end %>

    <div class="form-group">
    <label> Team </label><br>
        <%= f.collection_select(:team_id, current_user.remaining_teams, :id, :name, html: {class: "form-control form-control-lg"}) %>
    </div>

    <div class="form-group">
    <%= f.label :buy_in %><br>
    <%= f.check_box :buy_in, { checked: false }, true, false  %>
    </div>
    <div class="actions">
    <%= f.submit 'Create Pick', class: 'btn btn-info btn-block my-4'%>
    </div>

app/views/picks/edit.html.erb
<div class='body-container'>
    <div class="text-center">
        <%= render 'intro'%>
    </div>

    <div class="row">
        <div class="col-sm-6">  <%= render 'form'%> </div>
        <div class="col-sm-6"> 
            <% weekly_games.each do |g| %>
                <p> <%= matchup g%> </p>
            <% end %>
        </div>
    </div>
</div>

app/views/picks/index.html.erb
<div class='body-container'>
    <h1>All Picks:</h1>
    <br>
    <%= render partial: 'table', locals: { picks: @picks } %>
</div>

app/views/picks/new.html.erb
<div class='body-container'>
    <div>
        <%= render 'intro'%>
        <%= render 'form'%>
    </div>
</div>

app/views/picks/show.html.erb
<h1> Users Pick Page </h1>

<div class="column d-flex justify-content-center">
    <ul class="list-group">
        <% @picks.each do |p| %>
         <li class="list-group-item"> <p><%= matchup g %></p> </li>
    <% end %>
</div>