config/routes.rb
Rails.application.routes.draw do

  root 'users#home'
  
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}, path: :accounts

  resources :users, only: :show, path: :profile do
    resources :picks, except: :patch
  end

  resources :teams, only: [:index, :show]

  patch '/users/:user_id/picks/:id', to: 'picks#show', as: 'picks'

  get '/league', to: 'users#index'

  get '/schedule', to: 'games#schedule'

end

app/views/layouts/_alerts.html.erb
<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

app/views/layouts/_footer.html.erb
<div class="mt-5 pt-5 pb-5 footer">
<div class="container">
  <div class="row">
    <div class="col-lg-5 col-xs-12 about-company">
      <h2>About</h2>
      <p class="pr-5">My First Rails app consisting of an NFL Pick-Em game. All stats, schedule upto date using an API. </p>
    </div>
    <div class="col-lg-3 col-xs-12 links">
      <h4 class="mt-lg-0 mt-sm-3">Links</h4>
        <ul class="m-0 p-0">
          <li>- <a href="https://github.com/heartcombo/devise">Devise Gem</a></li>
          <li>- <a href="https://www.mysportsfeeds.com/">My Sports Feeds API</a></li>
          <li>- <a href="https://github.com/omniauth/omniauth">Omniauth</a></li>
          <li>- <a href="https://getbootstrap.com/">Bootstrap</a></li>
          <li>- <a href="https://github.com/rweng/pry-rails">Pry Rails</a></li>
        </ul>
    </div>
    <div class="col-lg-4 col-xs-12 location">
      
    </div>
  </div>
  <div class="row mt-5">
    <div class="col copyright">
      <p class=""><small class="text-black-50">© 2020. All Rights Reserved.</small></p>
    </div>
  </div>
</div>
</div>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NflpickemApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'NFL Pick-Em', root_path, class: 'navbar-brand'%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Schedule
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'League Schedule', schedule_path, class: 'nav-link'%>
              <%= link_to 'Team Schedule', teams_path, class: 'nav-link'%>
            </div>
          </li>
          
        <% if user_signed_in?%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              League
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%=link_to 'League Overview', league_path, class: "dropdown-item"%>
              <%if !(has_current_pick?) %>
                <%=link_to 'Make Weekly Pick', new_user_pick_path(current_user), class: "dropdown-item"%>
              <% end %>
                <%=link_to 'View & Edit Picks', user_picks_path(current_user), class: "dropdown-item"%>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="https://venmo.com/pbedrosian">Veno Buy-in</a>
            </div>
          </li>
        <%end%>

        </ul>
        <ul class="navbar-nav ml-auto"> 
            <li class="nav-item">
               <% if user_signed_in? %>
                <%= link_to 'Profile', user_path(current_user), class: 'nav-link'%>
              <% else %>
               <%= link_to 'Log In', new_user_session_path, class: 'nav-link'%> 
              <% end %> 
            </li> 
            <li class="nav-item">
               <% if user_signed_in? %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link'%>
              <% else %>
                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %> 
              <% end %> 
            </li>  
        </ul> 
      </div>
</nav>
<br>
    <div class='body-container', style="text-align:center;">
      <em ><%= render 'layouts/alerts' %> </em>
    </div>

app/views/layouts/application.html.erb
<%= render 'layouts/header'%>
    <%= yield %>
<%= render 'layouts/footer'%>